import React from 'react';
import { Document, Page, Text, View, pdf } from '@react-pdf/renderer';
import { formatCurrency, formatDate } from '../utils/format';
import { PdfHeader, PdfFooter, Section, FieldRow, styles } from './PdfBrand.jsx';

function ReceiptPdfDocument({ payment, merchant, payerName }) {
  return (
    <Document title={`KrishiBond Receipt ${payment.receiptNumber || ''}`}>
      <Page size="A4" style={styles.page}>
        <PdfHeader docLabel="Payment Receipt" />

        <Text style={styles.badge}>Demo Payment Gateway · Simulated Transaction</Text>
        <View style={styles.titleBlock}>
          <Text style={styles.title}>Payment Receipt</Text>
          <Text style={styles.subtitle}>
            Receipt #{payment.receiptNumber} · {formatDate(payment.paidAt, 'dd MMM yyyy, HH:mm')}
          </Text>
        </View>

        <Section title="Contract">
          <FieldRow label="Contract ID" value={`#${merchant?.contractId?.toString?.().slice(-6)}`} />
          <FieldRow label="Crop" value={merchant?.cropType} />
          <FieldRow label="Farmer" value={merchant?.farmerName} />
          <FieldRow label="Buyer" value={merchant?.buyerName} />
        </Section>

        <Section title="Payment">
          {payerName && <FieldRow label="Paid by" value={payerName} />}
          <FieldRow label="Transaction ID" value={payment.transactionId} />
          <FieldRow label="Order ID" value={payment.orderId} />
          <FieldRow label="Method" value={(payment.method || '').replace('_', ' ').toUpperCase()} />
          <FieldRow label="Status" value={payment.status === 'held' ? 'Paid (held in escrow)' : payment.status} />
        </Section>

        <Section title="Amount Paid">
          <View style={styles.amountBox}>
            <Text style={styles.amountLabel}>Total paid</Text>
            <Text style={styles.amountValue}>{formatCurrency(payment.totalAmount)}</Text>
            {payment.convenienceFee > 0 && (
              <Text style={styles.amountNote}>
                Includes {formatCurrency(payment.convenienceFee)} convenience fee
              </Text>
            )}
          </View>
        </Section>

        <Text style={styles.disclaimer}>
          This is a demo receipt generated by KrishiBond's simulated payment gateway for
          demonstration purposes only. No real financial transaction was processed and this
          document has no monetary value.
        </Text>

        <PdfFooter />
      </Page>
    </Document>
  );
}

export async function downloadReceiptPdf({ payment, merchant, payerName }) {
  const blob = await pdf(<ReceiptPdfDocument payment={payment} merchant={merchant} payerName={payerName} />).toBlob();
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `krishibond-receipt-${payment.receiptNumber || payment.id}.pdf`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export default ReceiptPdfDocument;
